# Generated by Django 3.2.23 on 2025-06-10 10:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('backend', '0001_initial'), ('backend', '0002_auto_20210629_2358'), ('backend', '0003_auto_20210630_0033'), ('backend', '0004_comment'), ('backend', '0005_order_amount_of_product'), ('backend', '0006_auto_20210721_0214'), ('backend', '0007_auto_20210722_0353'), ('backend', '0008_auto_20210722_0358'), ('backend', '0009_auto_20210722_0434'), ('backend', '0010_auto_20210722_0512'), ('backend', '0011_product_product_color_default'), ('backend', '0012_auto_20210724_0549'), ('backend', '0013_auto_20210724_0549'), ('backend', '0014_auto_20210724_2158'), ('backend', '0015_auto_20210724_2238'), ('backend', '0016_auto_20210724_2303'), ('backend', '0017_auto_20210724_2304')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('image', models.ImageField(upload_to='uploads/categories/')),
                ('base_price', models.FloatField(default=0.0)),
                ('max_amount_of_lettering_items', models.IntegerField(default=-1)),
                ('height', models.FloatField(default=0.0)),
                ('width', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='LetteringItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('price', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name_plural': 'lettering item categories',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=256)),
                ('stripe_charge_id', models.CharField(max_length=50)),
                ('amount', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('image', models.ImageField(blank=True, upload_to='uploads/products/')),
                ('only_on_default_color', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.category')),
                ('is_uploaded', models.BooleanField(default=False)),
                ('detail_image', models.ImageField(blank=True, upload_to='uploads/products_detail')),
            ],
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_in_hex', models.CharField(default='#000000', max_length=256, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}){1,2}$', 'only valid hex color code is accepted')])),
                ('color_nickname', models.CharField(default='add nickname', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.product')),
                ('product_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.productcolor')),
                ('amount', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=256)),
                ('image', models.ImageField(upload_to='uploads/comments/')),
                ('text', models.TextField(blank=True)),
                ('visible', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_color_default',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.productcolor'),
        ),
        migrations.CreateModel(
            name='LetteringItemVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lettering', models.CharField(max_length=256)),
                ('lettering_item_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.letteringitemcategory')),
                ('product_variation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lettering_item_variation_set', to='backend.productvariation')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user_email', models.CharField(max_length=256)),
                ('user_first_name', models.CharField(blank=True, max_length=256)),
                ('user_last_name', models.CharField(blank=True, max_length=256)),
                ('address1', models.CharField(default='Address line 1', max_length=1024)),
                ('address2', models.CharField(blank=True, default='Address line 2', max_length=1024, null=True)),
                ('ordered', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.payment')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.productvariation')),
            ],
        ),
    ]
